logging:
    level:
        root: INFO
        org:
            springframework:
                context: INFO
                web: WARN
                data:
                    root: DEBUG
                    convert: INFO
                    mongodb:
                        driver: WARN
                        core:
                            MongoTemplate: DEBUG
                    beans:
                        factory:
                            support: INFO
                    boot:
                      autoconfigure: INFO
            hibernate:
                validator: INFO
            apache: WARN
            mongodb:
                driver: WARN
        sun: INFO
        javax: INFO

spring:
    data:
        mongodb:
            uri: mongodb://campus:campus@localhost:37017/?authSource=admin
            database: CampusDB
