logging:
  level:
    root: INFO
    _org.springframework: INFO
    org:
        springframework:
            ui: INFO
            aop: INFO
            jdbc: INFO
            data: INFO
            context: INFO
            test: INFO
            beans: INFO
            orm: INFO
            core: INFO
            boot: INFO
            web: trace
            security: trace
        hibernate: INFO
        apache: INFO
        postgresql: INFO
        jboss.logging: INFO
    com.jobtrueffel.api: INFO
    sun.rmi: info
    jdk.event: info
    com.zaxxer: info

spring:
    data:
        mongodb:
            uri: mongodb://campus:campus@localhost:27017/campus?authSource=campus
            database: CampusDB
