version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 37017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: campus
      MONGO_INITDB_ROOT_PASSWORD: campus

  postgresql:
    image: "postgres"
    env_file:
      - postgres_db.env
    ports:
      - 3433:5432

